### ISSUE TITLE
Wha‘s the CUDA version?

### ISSUE THREAD

**Issue by shixuan7** [EdwardChasel/Spatial-Mamba#1]
Hi,
Thanks for contributing to this awesome work.
I have created a brand new Conda environment with python=3.10
When using CUDA 11.8: 
` cd kernels/dwconv2d && python3 setup.py install --user`
The setup process does not work and i get the following error:
`ERROR: RuntimeError: Error compiling objects for extension`
snippet:
`running install
/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing dwconv2d.egg-info/PKG-INFO
writing dependency_links to dwconv2d.egg-info/dependency_links.txt
writing top-level names to dwconv2d.egg-info/top_level.txt
reading manifest file 'dwconv2d.egg-info/SOURCES.txt'
writing manifest file 'dwconv2d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying Dwconv/dwconv_layer.py -> build/lib.linux-x86_64-cpython-310/Dwconv
running build_ext
/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'dwconv2d' extension
Emitting ninja build file /home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda-11.8/bin/nvcc  -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include/TH -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.8/include -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/include/python3.10 -c -c /home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu -o /home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/build/temp.linux-x86_64-cpython-310/depthwise_fwd/launch.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=dwconv2d -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
FAILED: /home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/build/temp.linux-x86_64-cpython-310/depthwise_fwd/launch.o 
/usr/local/cuda-11.8/bin/nvcc  -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include/TH -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.8/include -I/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/include/python3.10 -c -c /home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu -o /home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/build/temp.linux-x86_64-cpython-310/depthwise_fwd/launch.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=dwconv2d -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu(29): error: namespace "at" has no member "NoGradGuard"

/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu(63): error: namespace "at" has no member "NoGradGuard"

/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu(69): error: namespace "at" has no member "NoGradGuard"

/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/kernel.cuh(210): warning #177-D: variable "sparse_mask" was declared but never referenced
          detected during instantiation of "void <unnamed>::Dwconv2dKernelFP32<fh,fw,unroll_ow>(const <unnamed>::Param &, const float *, const float *, const float *, float *, __nv_bool) [with fh=31, fw=31, unroll_ow=4]" 
/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu(41): here

3 errors detected in the compilation of "/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/depthwise_fwd/launch.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wushixuan/yujun/PycharmProjects/11/Spatial-Mamba/kernels/dwconv2d/setup.py", line 5, in <module>
    setup(
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/install.py", line 97, in run
    self.do_egg_install()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/install.py", line 149, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 168, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 154, in call_command
    self.run_command(cmdname)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
    build_ext.build_extensions(self)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/wushixuan/yujun/app/anaconda3/envs/Spatial-Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
`RuntimeError: Error compiling objects for extension
`

env info:

> ubuntu 22.04
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

Package info:

> Package            Version
torch                   2.1.1+cu118
torchaudio              2.1.1+cu118
torchmetrics            1.5.1
torchvision             0.16.1+cu118
tqdm                    4.66.5
traitlets               5.14.3
triton                  2.1.0
ttach                   0.0.3

Could you please help me to solve this problem? Thanks.

**Comment by EdwardChasel** [comment]
For full alignment, we primarily used PyTorch 2.0.1 and CUDA 11.8. We have also tested it using PyTorch 2.x and CUDA 12.x on both NVIDIA V100 and A100 GPUs, encountering no issues. It might be some other factors.

**Comment by shixuan7** [comment]
> For full alignment, we primarily used PyTorch 2.0.1 and CUDA 11.8. We have also tested it using PyTorch 2.x and CUDA 12.x on both NVIDIA V100 and A100 GPUs, encountering no issues. It might be some other factors.

Thank you, I downgraded the torch version to 2.0.1 and solved the problem.
